spring:
  application:
    name: rightfind
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  profiles:
    active: @spring.profiles.active@
  main:
    allow-bean-definition-overriding: true
  batch:
    initialize-schema: always
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB